.TH CodeLite "1" "December 19, 2008" "CodeLite 1.0.2527"
.SH NAME
.B CodeLite
\- A lightweight and powerful C/C++ IDE
.SH SYNOPSIS
.B CodeLite
[\fI-v\fR] [\fI-h\fR] [\fI-l <num>\fR] [\fI-b <str>\fR] [\fIInput file\fR...]
.B codelite
[\fI-v\fR] [\fI-h\fR] [\fI-l <num>\fR] [\fI-b <str>\fR] [\fIInput file\fR...]
.SH DESCRIPTION
.TP
\fB\-v\fR, \fB\-\-version\fR
Print current version
.TP
\fB\-h\fR, \fB\-\-help\fR
Print usage
.TP
\fB\-l\fR, \fB\-\-line=\fR<num>
Open the file at a given line number
.TP
\fB\-b\fR, \fB\-\-basedir=\fR<str>
Use this path as CodeLite installation path
.TP
\fB\-v\fR, \fB\-\-version\fR
Print current version
.TP
\fB\-h\fR, \fB\-\-help\fR
Print usage
.TP
\fB\-l\fR, \fB\-\-line=\fR<num>
Open the file at a given line number
.TP
\fB\-b\fR, \fB\-\-basedir=\fR<str>
Use this path as CodeLite installation path
.SH COPYRIGHT
This manual page was written by Chow Loong Jin <hyperair@gmail.com> for the
Debian system (but may be used by others). Permission is granted to copy,
distribute and/or modify this document under the terms of the GNU General Public
License, Version 2 or any later version published by the Free Software
Foundation.

On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses.
