usr/lib/codelite/abbreviation.so
usr/lib/codelite/resources/abbreviation.accelerators usr/share/codelite/plugins/resources
usr/lib/codelite/resources/abbrev.png usr/share/codelite/plugins/resources
usr/lib/codelite/CodeFormatter.so
usr/lib/codelite/ContinuousBuild.so
usr/lib/codelite/resources/compfile.png usr/share/codelite/plugins/resources
usr/lib/codelite/Copyright.so
usr/lib/codelite/CppCheck.so
usr/lib/codelite/resources/cppcheck.png usr/share/codelite/plugins/resources
usr/bin/codelite_cppcheck usr/lib/codelite
usr/lib/codelite/cscope.so
usr/lib/codelite/SymbolView.so
usr/lib/codelite/resources/cscope.accelerators usr/share/codelite/plugins/resources
usr/lib/codelite/ExternalTools.so
usr/lib/codelite/resources/external_tools.accelerators usr/share/codelite/plugins/resources
usr/lib/codelite/Gizmos.so
usr/share/codelite/templates/gizmos
usr/lib/codelite/QmakePlugin.so
usr/lib/codelite/resources/qt* /usr/share/codelite/plugins/resources
usr/share/codelite/templates/projects/QmakeTestTmpl
usr/share/codelite/templates/projects/qmake*
usr/share/codelite/templates/qmake
usr/lib/codelite/SnipWiz.so
usr/lib/codelite/Subversion2.so
usr/lib/codelite/resources/svn* usr/share/codelite/plugins/resources
usr/lib/codelite/resources/wxfb_conflict.png usr/share/codelite/plugins/resources
usr/lib/codelite/resources/wxfb_modified.png usr/share/codelite/plugins/resources
usr/lib/codelite/resources/wxfb_ok.png usr/share/codelite/plugins/resources
usr/lib/codelite/UnitTestCPP.so
usr/share/codelite/templates/projects/UnitTest++
usr/share/codelite/src/unittest++1.3.tar.gz
usr/lib/codelite/wxformbuilder.so
usr/share/codelite/templates/formbuilder
