.TH "codelite_exec" "1"
.SH NAME
.B codelite_exec
\- small wrapper script to execute commands on Linux and keep the
console running until ENTER is pressed
.SH SYNOPSIS
.B codelite_exec
[\fINAME\fR=\fIVALUE\fR]... \fICOMMAND \fR[\fIARG\fR]...
.SH DESCRIPTION
Set each \fINAME\fR to \fIVALUE\fR in the environment and run \fICOMMAND\fR with arguments \fIARG\fR,
then keep the console running until ENTER is pressed.
.SH COPYRIGHT
This manual page was written by Chow Loong Jin <hyperair@gmail.com> for the
Debian system (but may be used by others). Permission is granted to copy,
distribute and/or modify this document under the terms of the GNU General Public
License, Version 2 or any later version published by the Free Software
Foundation.

On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses.
